services:
  - type: web
    name: estoque-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SPREADSHEET_ID
        value: 1O0g1CoxVvZWfOVPO2lECdj2RjrcZCXUJbZyoeFmsQiw